name: permissions
on:
   push:

env:
   TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 
        run: |
            echo "${TOKEN:0:9}[...]"
      - name: step2
        run: |
            echo "${TOKEN:0:9}[...]"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "${TOKEN:0:9}[...]"
