on:
  pull_request
  
jobs:
  super-linting:
     runs-on: self-hosted     
     steps:
       - uses: actions/checkout@v3

       - name: Super-Linter
         uses: super-linter/super-linter@v5.7.2
      
      - name: Multi-line
        run: |
          whoami
          env
